import type { SymbolItem } from "./types";

const raw: Array<[string, string, SymbolItem["family"], number, string[]]> = [
  ["tri-open", "△", "shape", 1, ["tri-filled", "tri-down"]],
  ["tri-filled", "▲", "shape", 1, ["tri-open", "tri-down-filled"]],
  ["tri-down", "▽", "shape", 2, ["tri-open", "tri-down-filled"]],
  ["tri-down-filled", "▼", "shape", 2, ["tri-filled", "tri-down"]],
  ["diamond-open", "◇", "shape", 1, ["diamond-filled", "hex-open"]],
  ["diamond-filled", "◆", "shape", 1, ["diamond-open", "square-filled"]],
  ["circle-open", "○", "shape", 1, ["circle-filled", "ring-dot"]],
  ["circle-filled", "●", "shape", 1, ["circle-open", "square-filled"]],
  ["square-open", "□", "shape", 1, ["square-filled", "diamond-open"]],
  ["square-filled", "■", "shape", 1, ["square-open", "diamond-filled"]],
  ["hex-open", "⬡", "shape", 2, ["hex-filled", "diamond-open"]],
  ["hex-filled", "⬢", "shape", 2, ["hex-open", "circle-filled"]],
  ["star", "✦", "shape", 2, ["spark", "crosshair"]],
  ["spark", "✧", "shape", 2, ["star", "asterisk"]],
  ["plus", "+", "terminal", 1, ["cross", "xmark"]],
  ["cross", "×", "terminal", 1, ["plus", "xmark"]],
  ["hash", "#", "terminal", 1, ["percent", "at"]],
  ["at", "@", "terminal", 1, ["hash", "amp"]],
  ["percent", "%", "terminal", 1, ["hash", "amp"]],
  ["amp", "&", "terminal", 1, ["percent", "at"]],
  ["question", "?", "terminal", 1, ["bang", "slash"]],
  ["bang", "!", "terminal", 1, ["question", "pipe"]],
  ["slash", "/", "code", 1, ["backslash", "caret"]],
  ["backslash", "\\", "code", 1, ["slash", "pipe"]],
  ["brackets", "[]", "code", 1, ["braces", "angles"]],
  ["braces", "{}", "code", 1, ["brackets", "angles"]],
  ["angles", "<>", "code", 1, ["brackets", "caret"]],
  ["pipe", "|", "code", 1, ["bang", "backslash"]],
  ["caret", "^", "code", 1, ["angles", "slash"]],
  ["tilde", "~", "code", 1, ["dash", "wave"]],
  ["dash", "-", "code", 1, ["tilde", "equals"]],
  ["equals", "=", "code", 1, ["dash", "double-eq"]],
  ["double-eq", "==", "code", 2, ["equals", "arrow-right-fat"]],
  ["arrow-up", "↑", "arrow", 1, ["arrow-down", "arrow-north"]],
  ["arrow-down", "↓", "arrow", 1, ["arrow-up", "arrow-south"]],
  ["arrow-left", "←", "arrow", 1, ["arrow-right", "arrow-west"]],
  ["arrow-right", "→", "arrow", 1, ["arrow-left", "arrow-east"]],
  ["arrow-north", "↟", "arrow", 2, ["arrow-up", "arrow-south"]],
  ["arrow-south", "↡", "arrow", 2, ["arrow-down", "arrow-north"]],
  ["arrow-west", "↞", "arrow", 2, ["arrow-left", "arrow-east"]],
  ["arrow-east", "↠", "arrow", 2, ["arrow-right", "arrow-west"]],
  ["arrow-right-fat", "=>", "code", 2, ["double-eq", "arrow-right"]],
  ["node", "⌬", "terminal", 2, ["target", "hex-open"]],
  ["target", "◎", "terminal", 2, ["circle-open", "node"]],
  ["ring-dot", "◉", "terminal", 2, ["circle-filled", "target"]],
  ["crosshair", "⊕", "terminal", 2, ["plus", "target"]],
  ["a7", "A7", "alphanumeric", 1, ["a1", "k7"]],
  ["k9", "K9", "alphanumeric", 1, ["k7", "x9"]],
  ["x1", "X1", "alphanumeric", 1, ["x9", "a1"]],
  ["z3", "Z3", "alphanumeric", 1, ["z8", "r3"]],
  ["n0", "N0", "alphanumeric", 1, ["m0", "n8"]],
  ["r5", "R5", "alphanumeric", 1, ["r3", "s5"]],
  ["a1", "A1", "alphanumeric", 2, ["a7", "x1"]],
  ["k7", "K7", "alphanumeric", 2, ["k9", "a7"]],
  ["x9", "X9", "alphanumeric", 2, ["x1", "k9"]],
  ["z8", "Z8", "alphanumeric", 2, ["z3", "n8"]],
  ["m0", "M0", "alphanumeric", 2, ["n0", "n8"]],
  ["r3", "R3", "alphanumeric", 2, ["r5", "z3"]],
  ["s5", "S5", "alphanumeric", 2, ["r5", "s8"]],
  ["n8", "N8", "alphanumeric", 2, ["n0", "z8"]],
  ["s8", "S8", "alphanumeric", 3, ["s5", "z8"]],
  ["sig-01", "01", "alphanumeric", 2, ["sig-10", "sig-0i"]],
  ["sig-10", "10", "alphanumeric", 2, ["sig-01", "sig-i0"]],
  ["sig-0i", "0I", "alphanumeric", 3, ["sig-01", "sig-i0"]],
  ["sig-i0", "I0", "alphanumeric", 3, ["sig-10", "sig-0i"]],
  ["wave", "≈", "code", 2, ["tilde", "equals"]],
  ["asterisk", "*", "terminal", 2, ["spark", "plus"]],
];

export const SYMBOLS: SymbolItem[] = raw.map(([id, glyph, family, difficulty, cousins]) => ({
  id,
  glyph,
  family,
  difficulty,
  cousins,
}));

export const symbolById = new Map(SYMBOLS.map((symbol) => [symbol.id, symbol]));
