import type { Theme } from "../game/types";

export const THEMES: Theme[] = [
  {
    id: "default",
    name: "Default Terminal",
    description: "Green and black hacker glass.",
    cost: 0,
    unlockedByDefault: true,
    colors: {
      background: "#020604",
      panel: "#071711",
      panelStrong: "#0c241b",
      text: "#dfffee",
      muted: "#7bd9b0",
      primary: "#28ff9b",
      secondary: "#39e7ff",
      danger: "#ff355d",
      warning: "#ffd36a",
      grid: "#123d2d",
      shadow: "rgba(40,255,155,0.28)",
    },
  },
  {
    id: "red-alert",
    name: "Red Alert",
    description: "Blacksite lockdown lighting.",
    cost: 150,
    unlockedByDefault: false,
    colors: {
      background: "#090204",
      panel: "#1b0709",
      panelStrong: "#310b0f",
      text: "#fff1f2",
      muted: "#ff9fac",
      primary: "#ff355d",
      secondary: "#ffb84a",
      danger: "#ff1749",
      warning: "#ffe06a",
      grid: "#431018",
      shadow: "rgba(255,53,93,0.32)",
    },
  },
  {
    id: "ice-firewall",
    name: "Ice Firewall",
    description: "Cold system breach optics.",
    cost: 200,
    unlockedByDefault: false,
    colors: {
      background: "#021018",
      panel: "#071c27",
      panelStrong: "#0b2d3d",
      text: "#effbff",
      muted: "#a0e8ff",
      primary: "#7df1ff",
      secondary: "#f6fbff",
      danger: "#ff4d7a",
      warning: "#b7f7ff",
      grid: "#123f52",
      shadow: "rgba(125,241,255,0.3)",
    },
  },
  {
    id: "gold-vault",
    name: "Gold Vault",
    description: "Premium heist vault pressure.",
    cost: 300,
    unlockedByDefault: false,
    colors: {
      background: "#070604",
      panel: "#171106",
      panelStrong: "#2c210c",
      text: "#fff8de",
      muted: "#e7c86d",
      primary: "#ffd36a",
      secondary: "#28ff9b",
      danger: "#ff355d",
      warning: "#ffe59b",
      grid: "#4a3714",
      shadow: "rgba(255,211,106,0.27)",
    },
  },
  {
    id: "ghost-protocol",
    name: "Ghost Protocol",
    description: "Purple/cyan stealth channel.",
    cost: 500,
    unlockedByDefault: false,
    colors: {
      background: "#050412",
      panel: "#0f0a25",
      panelStrong: "#1b113d",
      text: "#f0ebff",
      muted: "#b9a8ff",
      primary: "#9b7cff",
      secondary: "#39e7ff",
      danger: "#ff3f8d",
      warning: "#ffd36a",
      grid: "#261861",
      shadow: "rgba(57,231,255,0.28)",
    },
  },
];

export function getTheme(id: string): Theme {
  return THEMES.find((theme) => theme.id === id) ?? THEMES[0];
}
